In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [3]:
df = pd.read_csv('tough_dataset_Copy2.csv')
df.head()


id  Target A  Target B  LOAN_AMT  \
0  68407277  42405.00         0      3600   
1  68355089  60740.00         1     24700   
2  68341763  51907.68         0     20000   
3  66310712  51907.68         0     35000   
4  68476807     35.00         1     10400   

                                      Business Title  \
0                                    Account Manager   
1           EXECUTIVE DIRECTOR, BUSINESS DEVELOPMENT   
2  Maintenance Worker - Technical Services-Heatin...   
3  Maintenance Worker - Technical Services-Heatin...   
4                                  Temporary Painter   

              Civil Service Title              Division/Work Unit  \
0  CONTRACT REVIEWER (OFFICE OF L            Strategy & Analytics   
1  ADMINISTRATIVE BUSINESS PROMOT            Tech Talent Pipeline   
2              MAINTENANCE WORKER  Management Services Department   
3              MAINTENANCE WORKER  Management Services Department   
4                         PAINTER   Dept of Management & Planning   

                                     Job Description  \
0  Division of Economic & Financial Opportunity (...   
1  The New York City Department of Small Business...   
2  Under direct supervision, assist in the routin...   
3  Under direct supervision, assist in the routin...   
4  Responsibilities of selected candidates will i...   

                           Minimum Qual Requirements  \
0  1.\tA baccalaureate degree from an accredited ...   
1  1. A baccalaureate degree from an accredited c...   
2  1. Three years of full-time satisfactory exper...   
3  1. Three years of full-time satisfactory exper...   
4  1. Five years of full-time satisfactory experi...   

                                    Preferred Skills  ...             purpose  \
0  •\tExcellent interpersonal and organizationa...  ...  debt_consolidation   
1                                                NaN  ...      small_business   
2  1.  A High School Diploma or GED.  2.  CDL Dri...  ...    home_improvement   
3  1.  A High School Diploma or GED.  2.  CDL Dri...  ...  debt_consolidation   
4                                                NaN  ...      major_purchase   

                title zip_code addr_state    dti earliest_cr_line  \
0  Debt consolidation    190xx         PA   5.91            3-Aug   
1            Business    577xx         SD  16.06           Dec-99   
2                 NaN    605xx         IL  10.78           Aug-00   
3  Debt consolidation    076xx         NJ  17.06            8-Sep   
4      Major purchase    174xx         PA  25.37           Jun-98   

  last_pymnt_d last_pymnt_amnt next_pymnt_d last_credit_pull_d  
0       19-Jan          122.67          NaN             19-Mar  
1       16-Jun          926.35          NaN             19-Mar  
2       17-Jun        15813.30          NaN             19-Mar  
3       19-Feb          829.90       19-Apr             19-Mar  
4       16-Jul        10128.96          NaN             18-Mar  

[5 rows x 69 columns]

In [ ]:
df.isnull().sum().head(10)


id                             0
Target A                       1
Target B                       1
LOAN_AMT                       1
Business Title                 1
Civil Service Title            1
Division/Work Unit             1
Job Description                1
Minimum Qual Requirements     15
Preferred Skills             265
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1702 entries, 0 to 1701
Data columns (total 69 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   id                         1702 non-null   int64  
 1   Target A                   1701 non-null   float64
 2   Target B                   1701 non-null   float64
 3   LOAN_AMT                   1701 non-null   float64
 4   Business Title             1701 non-null   object 
 5   Civil Service Title        1701 non-null   object 
 6   Division/Work Unit         1701 non-null   object 
 7   Job Description            1701 non-null   object 
 8   Minimum Qual Requirements  1687 non-null   object 
 9   Preferred Skills           1437 non-null   object 
 10  Additional Information     1184 non-null   object 
 11  To Apply                   1700 non-null   object 
 12  Hours/Shift                515 non-null    object 
 13  Residency Requirement      1697 non-null   objec

In [ ]:

def missing_values_table(df):
   
    # Total missing values
    mis_val = df.isnull().sum()
    
    # Percentage of missing values
    mis_val_percent = 100 * df.isnull().sum() / len(df)
    
    # Make a table with the results
    mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
    
    # Rename the columns
    mis_val_table_columns = mis_val_table.rename(
    columns = {0 : 'Missing Values', 1 : '% of Total Values'})
    
    # Sort the table by percentage of missing descending
    # .iloc[:, 1]!= 0: filter on missing missing values not equal to zero
    mis_val_table_columns = mis_val_table_columns[
        mis_val_table_columns.iloc[:,1] != 0].sort_values(
    '% of Total Values', ascending=False).round(2)  # round(2), keep 2 digits
    
    # Print some summary information
    print("Dataset has {} columns.".format(df.shape[1]) + '\n' + 
    "There are {} columns that have missing values.".format(mis_val_table_columns.shape[0]))
    return mis_val_table_columns

In [ ]:

missing_values_table(df)

Dataset has 69 columns.
There are 68 columns that have missing values.


Missing Values  % of Total Values
TimeAfterBootcamp              1580              92.83
next_pymnt_d                   1500              88.13
HackathonReasons               1214              71.33
Hours/Shift                    1187              69.74
FrameworkWorkedWith             762              44.77
...                             ...                ...
Division/Work Unit                1               0.06
Civil Service Title               1               0.06
Business Title                    1               0.06
LOAN_AMT                          1               0.06
last_credit_pull_d                1               0.06

[68 rows x 2 columns]

In [ ]:
#Dropping the columns with missing values% >60 & unnecessary columns
X1 = df.drop(['Hours/Shift','HackathonReasons','TimeAfterBootcamp','next_pymnt_d','id','Target A','Target B','Posting Date','Posting Updated','Process Date','AgreeDisagree1','AgreeDisagree2','AgreeDisagree3'],axis = 1)
X1.head(3)


LOAN_AMT  ... last_credit_pull_d
0    3600.0  ...             19-Mar
1   24700.0  ...             19-Mar
2   20000.0  ...             19-Mar

[3 rows x 56 columns]

In [ ]:
X1.columns

Index(['LOAN_AMT', 'Business Title', 'Civil Service Title',
       'Division/Work Unit', 'Job Description', 'Minimum Qual Requirements',
       'Preferred Skills', 'Additional Information', 'To Apply',
       'Residency Requirement', 'FormalEducation', 'UndergradMajor',
       'CompanySize', 'DevType', 'YearsCoding', 'YearsCodingProf',
       'HopeFiveYears', 'JobSearchStatus', 'LastNewJob', 'UpdateCV',
       'CommunicationTools', 'TimeFullyProductive', 'EducationTypes',
       'SelfTaughtTypes', 'LanguageWorkedWith', 'LanguageDesireNextYear',
       'DatabaseWorkedWith', 'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'FrameworkWorkedWith',
       'FrameworkDesireNextYear', 'IDE', 'OperatingSystem', 'Methodology',
       'VersionControl', 'CheckInCode', 'AIDangerous', 'AIInteresting',
       'AIResponsible', 'AIFuture', 'Age', 'term', 'emp_length', 'loan_status',
       'pymnt_plan', 'url', 'purpose', 'title', 'zip_code', 'addr_state',
       'dti', '

In [ ]:
#Imputing the missing values
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imp = imp.fit(X1)
X2 = imp.transform(X1)


In [ ]:
x3= pd.DataFrame(X2)
x3.head(3)

0                                                  1   ...       54      55
0   3600                                    Account Manager  ...   122.67  19-Mar
1  24700           EXECUTIVE DIRECTOR, BUSINESS DEVELOPMENT  ...   926.35  19-Mar
2  20000  Maintenance Worker - Technical Services-Heatin...  ...  15813.3  19-Mar

[3 rows x 56 columns]

In [ ]:
x3.columns = ['LOAN_AMT', 'Business Title', 'Civil Service Title',
       'Division/Work Unit', 'Job Description', 'Minimum Qual Requirements',
       'Preferred Skills', 'Additional Information', 'To Apply',
       'Residency Requirement', 'FormalEducation', 'UndergradMajor',
       'CompanySize', 'DevType', 'YearsCoding', 'YearsCodingProf',
       'HopeFiveYears', 'JobSearchStatus', 'LastNewJob', 'UpdateCV',
       'CommunicationTools', 'TimeFullyProductive', 'EducationTypes',
       'SelfTaughtTypes',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'FrameworkWorkedWith',
       'FrameworkDesireNextYear', 'IDE', 'OperatingSystem', 'Methodology',
       'VersionControl', 'CheckInCode', 'AIDangerous', 'AIInteresting',
       'AIResponsible', 'AIFuture', 'Age', 'term', 'emp_length', 'loan_status',
       'pymnt_plan', 'url', 'purpose', 'title', 'zip_code', 'addr_state',
       'dti', 'earliest_cr_line', 'last_pymnt_d', 'last_pymnt_amnt',
       'last_credit_pull_d']

In [ ]:
x3.head()

LOAN_AMT  ... last_credit_pull_d
0     3600  ...             19-Mar
1    24700  ...             19-Mar
2    20000  ...             19-Mar
3    35000  ...             19-Mar
4    10400  ...             18-Mar

[5 rows x 56 columns]

In [ ]:
import seaborn as sns


In [ ]:
x4 = pd.get_dummies(x3,columns=['Business Title', 'Civil Service Title',
       'Division/Work Unit', 'Job Description', 'Minimum Qual Requirements',
       'Preferred Skills', 'Additional Information', 'To Apply',
       'Residency Requirement', 'FormalEducation', 'UndergradMajor',
       'CompanySize', 'DevType', 'YearsCoding', 'YearsCodingProf',
       'HopeFiveYears', 'JobSearchStatus', 'LastNewJob', 'UpdateCV',
       'CommunicationTools', 'TimeFullyProductive', 'EducationTypes',
       'SelfTaughtTypes','LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'FrameworkWorkedWith',
       'FrameworkDesireNextYear', 'IDE', 'OperatingSystem', 'Methodology',
       'VersionControl', 'CheckInCode', 'AIDangerous', 'AIInteresting',
       'AIResponsible', 'AIFuture', 'Age', 'term', 'emp_length', 'loan_status',
       'pymnt_plan', 'url', 'purpose', 'title', 'zip_code', 'addr_state',
       'dti', 'earliest_cr_line', 'last_pymnt_d', 'last_pymnt_amnt',
       'last_credit_pull_d'])


In [ ]:
print('Shape before encoding is {0} & after encoding is {1}'.format(x3.shape,x4.shape))

Shape before encoding is (1702, 56) & after encoding is (1702, 16452)


In [ ]:
x4.head()

LOAN_AMT  ...  last_credit_pull_d_19-Mar
0     3600  ...                          1
1    24700  ...                          1
2    20000  ...                          1
3    35000  ...                          1
4    10400  ...                          0

[5 rows x 16452 columns]

In [ ]:
x4['LOAN_AMT']= x4['LOAN_AMT'].astype(int)
x4['LOAN_AMT'].fillna(0)


0        3600
1       24700
2       20000
3       35000
4       10400
        ...  
1697     4000
1698    28800
1699    15000
1700    20000
1701    20000
Name: LOAN_AMT, Length: 1702, dtype: int64

In [ ]:
df['Target B'] = df['Target B'].fillna(0)
df['Target B'].astype(int)


0       0
1       1
2       0
3       0
4       1
       ..
1697    1
1698    0
1699    0
1700    1
1701    0
Name: Target B, Length: 1702, dtype: int64

In [ ]:
X = x4.values
y = df['Target B'].values
y1 = df['Target A'].values


#For Target B

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=0)


In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

In [ ]:
models = []
models.append(('Naive Bayes',GaussianNB()))
models.append(('RandomForest', RandomForestClassifier(n_estimators=10,random_state=0)))
models.append(('Decision Tree', DecisionTreeClassifier(random_state=0)))
models.append(('KNN', KNeighborsClassifier(n_neighbors = 30)))

In [ ]:
cl1 = KNeighborsClassifier(n_neighbors=30)
cl1.fit(X_train,y_train)
ypredd = cl1.predict(X_test)

In [ ]:
for name, model in models:
    print(name)
    model.fit(X_train, y_train)
    #Checking the cross_val_score
    score=cross_val_score(model,X,y,cv=10)
    print('Cross Val score is {0}'.format(score.mean()))
    
    
    # Make predictions.
    predictions = model.predict(X_test)
    # Compute the error.
    from sklearn.metrics import confusion_matrix
    print(confusion_matrix(predictions, y_test))
    print('')
    from sklearn.metrics import accuracy_score
    print('Accuracy Score: {0}'.format(accuracy_score(predictions,y_test)))
    print('\n')

Naive Bayes
Cross Val score is 0.6515755073959408
[[151  41]
 [109  40]]

Accuracy Score: 0.5601173020527859


RandomForest
Cross Val score is 0.7826143790849672
[[259  81]
 [  1   0]]

Accuracy Score: 0.7595307917888563


Decision Tree
Cross Val score is 0.6980220158238735
[[222  75]
 [ 38   6]]

Accuracy Score: 0.6686217008797654


KNN
Cross Val score is 0.7861369109047127
[[260  81]
 [  0   0]]

Accuracy Score: 0.7624633431085044




In [ ]:
m2 = RandomForestClassifier(n_estimators=10,random_state=0)
m2.fit(X_train,y_train)


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [ ]:
y_predz = m2.predict(X_test)

In [ ]:
cm = confusion_matrix(y_test,y_predz)
print('cm is {0}'.format(cm))
f1 = f1_score(y_test,y_predz)
print('f1 score is {0}'.format(f1))
ascore = accuracy_score(y_test,y_predz)
print('accuracy is {0}'.format(ascore))

cm is [[259   1]
 [ 81   0]]
f1 score is 0.0
accuracy is 0.7595307917888563


#For Target A

In [ ]:
y8 = df['Target A'].fillna(0)
y8

0       42405.00
1       60740.00
2       51907.68
3       51907.68
4          35.00
          ...   
1697    70000.00
1698    69940.00
1699    69940.00
1700    73305.00
1701        0.00
Name: Target A, Length: 1702, dtype: float64

In [ ]:
y8 = y8.apply(np.int64)

In [ ]:
X_train,X_test,y_train1,y_test1 = train_test_split(X,y8,test_size=0.20,random_state=0)


In [ ]:
y_train1.shape

(1361,)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures


In [ ]:

classifier1 = LinearRegression()
classifier1.fit(X_train, y_train1)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,f1_score,mean_squared_error

In [ ]:
y2_pred = classifier1.predict(X_test)
print("The mean squared error is {0}".format(mean_squared_error(y_test1,y2_pred,squared=False)))



The mean squared error is 17992.20184653107
